#!/bin/bash

FORMAT=$1

if [ -z $FORMAT ]; then
    FORMAT="html"
fi

for DIRECTORY in `find . -type d -maxdepth 1`
do
    if [ $DIRECTORY != "./script" ]; then
    if [ $DIRECTORY != "./.git" ]; then
    if [ $DIRECTORY != "." ]; then

        cd $DIRECTORY

        if [ -f Samenvatting.md ]; then
            echo "Converting $DIRECTORY/Samenvatting.md to $FORMAT"
            pandoc Samenvatting.md -o samenvatting.$FORMAT -c ../base.css
        fi

        cd ..

    fi
    fi
    fi
done

# pandoc $MD_PATH -o $HTML_PATH -c ../base.css
