#!/bin/bash

if [ -z `which kicker` ]; then
    echo "Please install 'Kicker' by running 'gem install kicker'."
    exit 1;
fi

DIRECTORY=$1

if [ -z "$DIRECTORY" ]; then
    echo "USAGE:"
    echo "$ script/watch <course>"
    exit 0;
fi

if [[ "--mathjax" == $2 ]]; then
    MATHJAX="--mathjax='http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'"
else
    MATHJAX=""
fi

MD_PATH="$DIRECTORY/Samenvatting.md"
HTML_PATH="$DIRECTORY/samenvatting.html"

kicker -e "pandoc $MD_PATH -o $HTML_PATH -c ../base.css $MATHJAX" $MD_PATH
