#!/bin/bash

if [ -z `which kicker` ]; then
    read -p "I need the 'kicker' gem to work. Would you like to install it? (y/n) " -n 1 -r;
    echo    # (optional) move to a new line
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        gem install kicker;
    else
        echo "Please install 'Kicker' by running 'gem install kicker'."
        exit 1;
    fi
fi

DIRECTORY=$1

if [ -z "$DIRECTORY" ]; then
    echo "USAGE:"
    echo "$ script/watch <course>"
    exit 0;
fi

if [[ "--mathjax" == $2 ]]; then
    MATHJAX="--mathjax"
else
    MATHJAX=""
fi

MD_PATH="$DIRECTORY/Samenvatting.md"
HTML_PATH="$DIRECTORY/samenvatting.html"

kicker -e "pandoc $MD_PATH -o $HTML_PATH -c ../base.css $MATHJAX" $MD_PATH
