#!/bin/bash

if [ -z `which kicker` ]; then
    echo "Please install 'Kicker' by running 'gem install kicker'."
    exit 1;
fi

COURSE=$1

if [ -z "$COURSE" ]; then
    echo "USAGE:"
    echo "$ script/watch <course>"
    exit 0;
fi

MD_PATH="$COURSE/Samenvatting.md"
HTML_PATH="$COURSE/samenvatting.html"

kicker -e "pandoc $MD_PATH -o $HTML_PATH -c ../base.css" $MD_PATH &
watch -n 60 script/deploy &
open "$MD_PATH $HTML_PATH"
